export type IPokemon = {
  name: string;
  types: TYPES[];
};

export enum TYPES {
  normal = "normal",
  fire = "fire",
  water = "water",
  electric = "electric",
  grass = "grass",
  ice = "ice",
  fighting = "fighting",
  poison = "poison",
  ground = "ground",
  flying = "flying",
  psychic = "psychic",
  bug = "bug",
  rock = "rock",
  ghost = "ghost",
  dragon = "dragon",
  dark = "dark",
  steel = "steel",
  fairy = "fairy",
}

export const TYPEORDER = [
  TYPES.normal,
  TYPES.fire,
  TYPES.water,
  TYPES.electric,
  TYPES.grass,
  TYPES.ice,
  TYPES.fighting,
  TYPES.poison,
  TYPES.ground,
  TYPES.flying,
  TYPES.psychic,
  TYPES.bug,
  TYPES.rock,
  TYPES.steel,
  TYPES.ghost,
  TYPES.dark,
  TYPES.dragon,
  TYPES.fairy,
];

export const TYPEINFO = {
  [TYPES.normal]: {
    name: "normal",
    color: "#B1B1BA",
    font: "black",
  },
  [TYPES.fire]: {
    name: "fire",
    color: "#F55E57",
    font: "black",
  },
  [TYPES.water]: {
    name: "water",
    color: "#54AFF4",
    font: "black",
  },
  [TYPES.electric]: {
    name: "electric",
    color: "#F2CB2F",
    font: "black",
  },
  [TYPES.grass]: {
    name: "grass",
    color: "#61D879",
    font: "black",
  },
  [TYPES.ice]: {
    name: "ice",
    color: "#5BCBB7",
    font: "black",
  },
  [TYPES.fighting]: {
    name: "fighting",
    color: "#B1434E",
    font: "white",
  },
  [TYPES.poison]: {
    name: "poison",
    color: "#D96DF5",
    font: "black",
  },
  [TYPES.ground]: {
    name: "ground",
    color: "#EB8E3E",
    font: "black",
  },
  [TYPES.flying]: {
    name: "flying",
    color: "#A8C2FB",
    font: "black",
  },
  [TYPES.psychic]: {
    name: "psychic",
    color: "#E56CAC",
    font: "black",
  },
  [TYPES.bug]: {
    name: "bug",
    color: "#A9C643",
    font: "black",
  },
  [TYPES.rock]: {
    name: "rock",
    color: "#D2BA5C",
    font: "black",
  },
  [TYPES.ghost]: {
    name: "ghost",
    color: "#6D76C1",
    font: "white",
  },
  [TYPES.dragon]: {
    name: "dragon",
    color: "#7D68DC",
    font: "white",
  },
  [TYPES.dark]: {
    name: "dark",
    color: "#4B3B2F",
    font: "white",
  },
  [TYPES.steel]: {
    name: "steel",
    color: "#B8CCD1",
    font: "black",
  },
  [TYPES.fairy]: {
    name: "fairy",
    color: "#F6AAFA",
    font: "black",
  },
};

export const TYPECHART: {
  [attackType in TYPES]: {
    [defenseType in TYPES]?: number;
  };
} = {
  [TYPES.normal]: {
    [TYPES.rock]: 0.5,
    [TYPES.ghost]: 0,
    [TYPES.steel]: 0.5,
  },
  [TYPES.fire]: {
    [TYPES.fire]: 0.5,
    [TYPES.water]: 0.5,
    [TYPES.grass]: 2,
    [TYPES.ice]: 2,
    [TYPES.bug]: 2,
    [TYPES.rock]: 0.5,
    [TYPES.dragon]: 0.5,
    [TYPES.steel]: 2,
  },
  [TYPES.water]: {
    [TYPES.fire]: 2,
    [TYPES.water]: 0.5,
    [TYPES.grass]: 0.5,
    [TYPES.ground]: 2,
    [TYPES.rock]: 2,
    [TYPES.dragon]: 0.5,
  },
  [TYPES.electric]: {
    [TYPES.water]: 2,
    [TYPES.electric]: 0.5,
    [TYPES.grass]: 0.5,
    [TYPES.ground]: 0,
    [TYPES.flying]: 2,
    [TYPES.dragon]: 0.5,
  },
  [TYPES.grass]: {
    [TYPES.fire]: 0.5,
    [TYPES.water]: 2,
    [TYPES.grass]: 0.5,
    [TYPES.poison]: 0.5,
    [TYPES.ground]: 2,
    [TYPES.flying]: 0.5,
    [TYPES.bug]: 0.5,
    [TYPES.rock]: 2,
    [TYPES.dragon]: 0.5,
    [TYPES.steel]: 0.5,
  },
  [TYPES.ice]: {
    [TYPES.fire]: 0.5,
    [TYPES.water]: 0.5,
    [TYPES.grass]: 2,
    [TYPES.ice]: 0.5,
    [TYPES.ground]: 2,
    [TYPES.flying]: 2,
    [TYPES.dragon]: 2,
    [TYPES.steel]: 0.5,
  },
  [TYPES.fighting]: {
    [TYPES.normal]: 2,
    [TYPES.ice]: 2,
    [TYPES.poison]: 0.5,
    [TYPES.flying]: 0.5,
    [TYPES.psychic]: 0.5,
    [TYPES.bug]: 0.5,
    [TYPES.rock]: 2,
    [TYPES.ghost]: 0,
    [TYPES.dark]: 2,
    [TYPES.steel]: 2,
    [TYPES.fairy]: 0.5,
  },
  [TYPES.poison]: {
    [TYPES.grass]: 2,
    [TYPES.poison]: 0.5,
    [TYPES.ground]: 0.5,
    [TYPES.rock]: 0.5,
    [TYPES.ghost]: 0.5,
    [TYPES.steel]: 0,
    [TYPES.fairy]: 2,
  },
  [TYPES.ground]: {
    [TYPES.fire]: 2,
    [TYPES.electric]: 2,
    [TYPES.grass]: 0.5,
    [TYPES.poison]: 2,
    [TYPES.flying]: 0,
    [TYPES.bug]: 0.5,
    [TYPES.rock]: 2,
    [TYPES.steel]: 2,
  },
  [TYPES.flying]: {
    [TYPES.electric]: 0.5,
    [TYPES.grass]: 2,
    [TYPES.fighting]: 2,
    [TYPES.bug]: 2,
    [TYPES.rock]: 0.5,
    [TYPES.steel]: 0.5,
  },
  [TYPES.psychic]: {
    [TYPES.fighting]: 2,
    [TYPES.poison]: 2,
    [TYPES.psychic]: 0.5,
    [TYPES.dark]: 0,
    [TYPES.steel]: 0.5,
  },
  [TYPES.bug]: {
    [TYPES.fire]: 0.5,
    [TYPES.grass]: 2,
    [TYPES.fighting]: 0.5,
    [TYPES.poison]: 0.5,
    [TYPES.flying]: 0.5,
    [TYPES.psychic]: 2,
    [TYPES.ghost]: 0.5,
    [TYPES.dark]: 2,
    [TYPES.steel]: 0.5,
    [TYPES.fairy]: 0.5,
  },
  [TYPES.rock]: {
    [TYPES.fire]: 2,
    [TYPES.ice]: 2,
    [TYPES.fighting]: 0.5,
    [TYPES.ground]: 0.5,
    [TYPES.flying]: 2,
    [TYPES.bug]: 2,
    [TYPES.steel]: 0.5,
  },
  [TYPES.ghost]: {
    [TYPES.normal]: 0,
    [TYPES.psychic]: 2,
    [TYPES.ghost]: 2,
    [TYPES.dark]: 0.5,
  },
  [TYPES.dragon]: {
    [TYPES.dragon]: 2,
    [TYPES.steel]: 0.5,
    [TYPES.fairy]: 0,
  },
  [TYPES.dark]: {
    [TYPES.fighting]: 0.5,
    [TYPES.psychic]: 2,
    [TYPES.ghost]: 2,
    [TYPES.dark]: 0.5,
    [TYPES.fairy]: 0.5,
  },
  [TYPES.steel]: {
    [TYPES.fire]: 0.5,
    [TYPES.water]: 0.5,
    [TYPES.ice]: 2,
    [TYPES.rock]: 2,
    [TYPES.steel]: 0.5,
    [TYPES.fairy]: 2,
  },
  [TYPES.fairy]: {
    [TYPES.fire]: 0.5,
    [TYPES.fighting]: 2,
    [TYPES.poison]: 0.5,
    [TYPES.dragon]: 2,
    [TYPES.dark]: 2,
    [TYPES.steel]: 0.5,
  },
};
export default TYPECHART;
